---
name: json lint
enable-email-notifications: true
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    name: json lint
    steps:
      - uses: actions/checkout@v6
      - uses: actions/markdownlint-cli2-action@v21
        with:
          globs: |
            **/*.md
            !out/*.md
            !jsonresume-theme-curzy-custom/**/*.md
      - run: jq . cv-*.json -e
