---
name: json lint
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    name: json lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/markdownlint-cli2-action@v17
        with:
          globs: |
            **/*.md
            !out/*.md
            !jsonresume-theme-curzy-custom/**/*.md
      - run: jq . cv-*.json -e
